20170408T120037.216: fb_browse.py: 53:         spider_closed: INFO: Message - Logout Successfully
20170408T121930.899: fb_browse.py: 53:         spider_closed: INFO: Message - Logout Successfully
20170408T123546.114: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T123755.612: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T123956.572: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T124159.785: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T124354.596: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T124556.625: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T124800.797: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T124954.540: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T125154.356: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T125350.305: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T125554.241: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T125758.0: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T130001.334: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T130208.321: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T130409.911: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T130612.338: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T130812.368: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T131002.957: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T131201.198: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T131407.463: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T131603.376: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T131811.277: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T132015.873: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T132214.980: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T132359.648: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T132530.78: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T132644.626: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T132752.990: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T132851.812: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T132946.865: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133047.65: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133144.479: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133231.569: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133314.365: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133352.884: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133430.567: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133459.675: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133526.210: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133547.189: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133607.976: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133620.717: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133637.598: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133652.802: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133706.816: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133723.827: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133739.330: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133756.11: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133812.117: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133827.606: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133842.955: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133858.410: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133911.286: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133927.82: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133942.296: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T133955.303: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134008.814: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134023.787: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134041.383: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134058.345: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134114.511: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134128.135: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134141.178: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134158.302: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134213.781: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134228.813: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134245.640: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134259.52: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134312.722: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134326.339: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134343.398: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134355.59: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134411.520: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134428.213: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134444.914: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134457.769: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134512.93: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134526.425: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134540.458: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134554.938: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134609.434: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134624.812: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134637.316: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134651.932: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134706.806: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134722.333: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134738.361: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134753.639: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134807.727: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134823.829: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134839.379: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134853.897: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134904.111: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134916.116: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134932.630: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134946.300: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T134959.811: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135017.766: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135034.884: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135048.471: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135104.149: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135118.673: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135132.679: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135145.787: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135159.681: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135215.880: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135230.911: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135244.415: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135258.819: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135313.820: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135330.369: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135342.445: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135354.210: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135407.901: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135422.660: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135437.583: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135454.77: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135511.188: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135526.888: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135542.102: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135557.512: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135612.379: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135627.22: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135642.242: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135655.742: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135712.116: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135729.89: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135743.533: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135756.666: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135810.407: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135824.483: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135838.194: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135853.569: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135907.461: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135917.918: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135932.981: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T135947.831: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140002.498: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140017.733: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140035.656: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140050.729: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140107.396: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140119.779: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140133.80: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140147.77: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140204.181: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140216.774: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140233.505: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140250.546: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140305.28: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140318.397: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140330.910: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140348.467: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140401.39: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140414.870: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140432.126: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140446.161: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140457.315: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140509.289: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140523.200: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140535.59: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140548.423: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140603.9: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140614.188: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140629.91: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140645.584: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140700.199: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140713.692: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140731.54: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140745.881: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140803.363: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140817.828: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140831.624: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140842.920: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140900.380: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140916.703: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140933.668: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140942.340: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140945.982: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140954.615: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T140958.204: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141006.740: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141015.741: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141021.154: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141028.391: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141034.162: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141042.991: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141050.802: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141057.205: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141106.187: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141114.494: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141120.347: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141127.61: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141132.350: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141140.56: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141148.768: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141155.719: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141202.705: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141209.578: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141217.815: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141226.523: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141230.451: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141238.438: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141247.394: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141255.448: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141304.132: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141309.111: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141317.408: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141325.161: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141334.231: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141342.607: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141350.756: fb_browse.py: 394:         parse_profile: ERROR: Error: Traceback (most recent call last):
  File "/root/Facebook/Facebook/spiders/fb_browse.py", line 385, in parse_profile
    self.cur.execute(selectauxkeys_params%(keyf,sk))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 8466 (char 8465)

20170408T141357.707: fb_browse.py: 53:         spider_closed: INFO: Message - Logout Successfully
20170409T001105.936: fb_browse.py: 53:         spider_closed: INFO: Message - Logout Successfully
20170409T005456.780: fb_browse.py: 53:         spider_closed: INFO: Message - Logout Successfully
20170409T011812.589: fb_browse.py: 53:         spider_closed: INFO: Message - Logout Successfully
